language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_github_packages:
  - rondolab/MR-PRESSO
  - mrcieu/MRInstruments
  - mrcieu/ieugwasr
  - mrcieu/MRInstruments
  - WSpiller/RadialMR
  - gqi/MRMix

warnings_are_errors: false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
